import type { ProjectVideo } from "./types";

type ProjectDef = {
  slug: string;
  assetFolder: string;
  order: number;
  featured: boolean;
  name: string;
  tagline: string;
  category: string;
  categoryGroup: "Product" | "Marketing" | "Brand" | "Process";
  role: string;
  timeline: string;
  tools: string[];
  problem: string;
  summary: string;
  metrics: { label: string; value: string; detail?: string }[];
  highlights: string[];
  process: { title: string; body: string; bullets?: string[] }[];
  outcomes: { title: string; body: string }[];
  deliverables: string[];
  proves: string;
  coverFile?: string;
  extraVideos?: ProjectVideo[];
  accent: string;
  accentMuted: string;
};

export const projectDefinitions: ProjectDef[] = [
  {
    slug: "karto",
    assetFolder: "Karto",
    order: 0,
    featured: true,
    name: "Karto",
    tagline: "Multi-sided marketplace for hardware & landscaping supplies — customer, store, rider, and web",
    category: "Marketplace · Mobile + Web",
    categoryGroup: "Product",
    role: "UI/UX Product Designer",
    timeline: "12 weeks",
    tools: ["Figma", "Design Systems", "Prototyping", "Multi-platform UI"],
    problem:
      "Hardware and landscaping shoppers struggled to find nearby suppliers with clear delivery, while stores and riders needed separate tools to accept orders, fulfill, and get paid — without a unified product experience.",
    summary:
      "Designed the full Karto ecosystem end-to-end: a customer mobile app for discovery and ordering, a store app for order acceptance and earnings, a rider app for pickup and delivery ops, and a marketing/web surface for acquisition, vendor onboarding, and trust.",
    metrics: [
      { label: "Screens delivered", value: "108+", detail: "across 4 product surfaces" },
      { label: "Product apps", value: "4", detail: "customer, store, rider, web" },
      { label: "Core flows", value: "10+", detail: "search, order, dispatch, payouts" },
    ],
    highlights: [
      "Location-based customer discovery & checkout",
      "Store order acceptance & earnings",
      "Rider pickup, delivery, and wallet flows",
    ],
    process: [
      {
        title: "Multi-persona mapping",
        body: "Mapped jobs-to-be-done for customers (search → order → track), stores (accept → prepare → handoff), and riders (claim → pickup → deliver → withdraw).",
      },
      {
        title: "Shared design language",
        body: "Built a consistent green-accent system, card patterns, and status states so all four surfaces feel like one product family.",
      },
      {
        title: "Ops-ready flows",
        body: "Designed real operational states — declined orders, comments, payouts, schedules, and edge cases — not only happy paths.",
      },
    ],
    outcomes: [
      {
        title: "Complete marketplace suite",
        body: "One cohesive UI system spanning consumer, merchant, courier, and web acquisition.",
      },
      {
        title: "Clear delivery UX",
        body: "Order lifecycle screens cover placement, store acceptance, rider assignment, and arrival with readable status hierarchy.",
      },
    ],
    deliverables: ["108+ UI screens", "4 platform surfaces", "Marketing & onboarding pages"],
    proves: "Multi-sided marketplace UX across mobile + web",
    coverFile: "web/Homepage.png",
    accent: "#76C783",
    accentMuted: "rgba(118, 199, 131, 0.18)",
  },
  {
    slug: "handy-hub",
    assetFolder: "HandyHub",
    order: 1,
    featured: true,
    name: "Handy Hub",
    tagline: "On-demand home services app — discover, book, and manage local professionals",
    category: "Mobile · Services Marketplace",
    categoryGroup: "Product",
    role: "UI/UX Product Designer",
    timeline: "10 weeks",
    tools: ["Figma", "Prototyping", "Mobile Patterns", "User Flows"],
    problem:
      "Booking home services is fragmented — users struggle to find nearby trusted professionals, compare options, schedule appointments, and manage cancellations without bouncing between apps and calls.",
    summary:
      "Designed Handy Hub end-to-end: splash & onboarding, service discovery by category and location, provider detail & booking, guest appointments, ratings & search, cancellations, and full profile settings including wallet, addresses, and business join flows.",
    metrics: [
      { label: "Screens delivered", value: "164+", detail: "across 6 product flows" },
      { label: "Core flows", value: "6", detail: "auth, home, booking, search, cancel, profile" },
      { label: "Service categories", value: "8+", detail: "cleaning, repair, laundry & more" },
    ],
    highlights: [
      "Location-based discovery & nearby providers",
      "Appointment booking with date, time & payment",
      "Guest booking, ratings, inbox & cancellations",
    ],
    process: [
      {
        title: "Service journey mapping",
        body: "Mapped the full loop from splash → discover → book → confirm → manage/cancel, including guest paths and edge states like invalid date/time.",
      },
      {
        title: "Trust & clarity UX",
        body: "Designed provider cards with ratings/distance, confirmed appointment overviews, calendar/maps deep-links, and clear cancellation policy.",
      },
      {
        title: "Account & growth surfaces",
        body: "Built profile settings for wallet, cards, addresses, favorites, support, and joining as a business — supporting retention and marketplace supply.",
      },
    ],
    outcomes: [
      {
        title: "Complete booking product",
        body: "One cohesive mobile experience covering discovery, scheduling, messaging, and post-booking management.",
      },
      {
        title: "Operational edge cases",
        body: "Cancellation, reschedule, invalid slots, and guest appointment flows designed alongside happy paths.",
      },
    ],
    deliverables: ["164+ UI screens", "6 flow groups", "Auth, booking & profile systems"],
    proves: "Services marketplace & booking UX",
    coverFile: "Home detail/Home screen.png",
    accent: "#5B4BDB",
    accentMuted: "rgba(91, 75, 219, 0.16)",
  },
  {
    slug: "cravely-vendor",
    assetFolder: "cravelyvendorapp",
    order: 2,
    featured: true,
    name: "Cravely Vendor",
    tagline: "Multi-vendor food delivery admin platform for operations at scale",
    category: "SaaS · B2B Dashboard",
    categoryGroup: "Product",
    role: "Lead UI/UX Designer",
    timeline: "8 weeks",
    tools: ["Figma", "Prototyping", "Design Systems", "Dev Handoff"],
    problem:
      "Operations teams managing restaurants, riders, zones, and payouts needed a single dashboard — legacy tools scattered data across screens and slowed daily decisions.",
    summary:
      "Designed the Cravely vendor and admin experience end-to-end: KPI dashboards, dispatch, zone radius tools, coupon management, payment flows, and role-based navigation — built for clarity under operational pressure.",
    metrics: [
      { label: "Screens delivered", value: "31+", detail: "production-ready UI frames" },
      { label: "Core modules", value: "12", detail: "dashboard, dispatch, zones, payments & more" },
      { label: "Prototype flows", value: "3", detail: "recorded walkthrough videos" },
    ],
    highlights: ["KPI dashboard with trend cards & sales tables", "Zone & rider management", "Multi-step payment & coupon flows"],
    process: [
      {
        title: "Operational research",
        body: "Mapped admin jobs-to-be-done: morning KPI review, dispatch triage, zone updates, and payout requests — prioritizing screens by daily frequency.",
      },
      {
        title: "Information architecture",
        body: "Structured navigation around Management, General settings, and Home overview — reducing depth for high-frequency tasks.",
      },
      {
        title: "UI system & handoff",
        body: "Built reusable patterns for stat cards, data tables, filters, and form wizards with consistent spacing and component variants.",
      },
    ],
    outcomes: [
      { title: "Actionable dashboard", body: "Executives and ops leads scan users, vendors, stores, and riders in one view with trend indicators." },
      { title: "End-to-end ops flows", body: "Dispatch, zones, withdrawals, and configuration screens cover the full vendor lifecycle." },
    ],
    deliverables: ["31+ UI screens", "3 prototype videos", "Component-ready layouts"],
    proves: "Complex B2B SaaS & data-heavy product design",
    coverFile: "Dashboard.png",
    extraVideos: [
      { src: "/work-assets/cravelyvendorapp/WebCravelyvendorapp.webm", title: "Vendor App Walkthrough" },
      { src: "/work-assets/cravelyvendorapp/Webcravely2VendorApp.webm", title: "Vendor Flow Demo" },
      { src: "/work-assets/cravelyvendorapp/WebcravelystartVendorApp.webm", title: "Onboarding Flow" },
    ],
    accent: "#2563EB",
    accentMuted: "rgba(37, 99, 235, 0.15)",
  },
  {
    slug: "iot-smart-home",
    assetFolder: "iotsmarthome",
    order: 2,
    featured: false,
    name: "SmartHome IoT",
    tagline: "Connected home mobile app & admin dashboard for devices, automation, and security",
    category: "IoT · Mobile + Web",
    categoryGroup: "Product",
    role: "UI/UX Product Designer",
    timeline: "10 weeks",
    tools: ["Figma", "Variables", "Prototyping", "Responsive UI"],
    problem:
      "Smart home users juggle dozens of devices across rooms — existing apps buried controls and left admins without system-level visibility.",
    summary:
      "Designed a dual-surface IoT product: a consumer mobile app for devices, automations, and security — plus a web admin dashboard for overview, diagnostics, energy, and user management.",
    metrics: [
      { label: "Total screens", value: "54+", detail: "mobile app + web dashboard" },
      { label: "Platforms", value: "2", detail: "iOS-style app & admin web" },
      { label: "Feature areas", value: "8+", detail: "devices, rooms, security, energy" },
    ],
    highlights: ["Dark-theme mobile home hub", "Automation & scene builder", "Admin overview & system health"],
    process: [
      { title: "Dual-persona framing", body: "Separated homeowner quick actions from admin monitoring — each surface optimized for its context." },
      { title: "Device-first IA", body: "Organized around rooms, devices, automations, and security rather than feature silos." },
      { title: "Trust & status UX", body: "Clear online/offline states, alerts, and system health patterns for high-stakes home control." },
    ],
    outcomes: [
      { title: "Mobile control center", body: "At-a-glance lights, climate, and security with quick actions and device toggles." },
      { title: "Admin command center", body: "Dashboard with device tables, diagnostics, and energy insights for property managers." },
    ],
    deliverables: ["44 mobile screens", "9 dashboard screens", "PDF documentation"],
    proves: "IoT UX, mobile + SaaS, dark UI craft",
    coverFile: "App/Home page.png",
    accent: "#38BDF8",
    accentMuted: "rgba(56, 189, 248, 0.15)",
  },
  {
    slug: "grocery-store",
    assetFolder: "grocerystore",
    order: 3,
    featured: true,
    name: "Grocery Delivery",
    tagline: "Full-stack grocery commerce app — browse, cart, checkout, and account",
    category: "Mobile · E-commerce",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "9 weeks",
    tools: ["Figma", "Auto Layout", "Prototyping", "Mobile Patterns"],
    problem:
      "Grocery shoppers abandon apps when discovery is slow, carts feel opaque, and delivery rules are unclear.",
    summary:
      "Designed a complete grocery delivery experience: category browsing, deals, product detail, cart states, checkout, profile, order history, ratings, and edge cases like minimum spend limits.",
    metrics: [
      { label: "Screens", value: "59+", detail: "full product flow coverage" },
      { label: "Flows", value: "6+", detail: "shop, cart, pay, profile, deals" },
      { label: "Edge states", value: "5+", detail: "empty cart, limits, errors" },
    ],
    highlights: ["Category-led home feed", "Deal badges & promo banners", "Cart, payment & order history"],
    process: [
      { title: "Commerce journey mapping", body: "Mapped discovery → product → cart → payment → post-order rating as one coherent loop." },
      { title: "Merchandising patterns", body: "Horizontal category rails, special offers, and quick-meal sections for scan-friendly shopping." },
      { title: "Edge-case design", body: "Empty cart, minimum spend, forgot password, and delivery screens designed alongside happy paths." },
    ],
    outcomes: [
      { title: "High-density mobile UI", body: "Readable product cards, pricing, and add-to-cart affordances at thumb reach." },
      { title: "Account & retention", body: "Profile, favorites, order history, and rating flows support repeat purchase." },
    ],
    deliverables: ["59+ mobile screens", "Profile flow video", "Checkout & payment states"],
    proves: "Mobile e-commerce & conversion-focused UX",
    coverFile: "HomeScreen.png",
    extraVideos: [{ src: "/work-assets/grocerystore/ProfileflowgroceryApp.webm", title: "Profile Flow" }],
    accent: "#7C3AED",
    accentMuted: "rgba(124, 58, 237, 0.15)",
  },
  {
    slug: "crossfade",
    assetFolder: "crossfade",
    order: 4,
    featured: true,
    name: "CrossFade",
    tagline: "Streaming app for music, podcasts, video, and live radio",
    category: "Mobile · Media",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "7 weeks",
    tools: ["Figma", "Prototyping", "iOS Patterns", "Motion Specs"],
    problem:
      "Media apps often silo content types — users switch apps for music vs podcasts vs video, losing continuity and personalization.",
    summary:
      "Designed CrossFade as a unified streaming experience with segmented home feeds, rich music playback, lyrics, search, auth flows, and live radio — dark UI with bold content-forward layout.",
    metrics: [
      { label: "Screens", value: "17+", detail: "auth, home, playback, search" },
      { label: "Content modes", value: "4", detail: "music, podcasts, video, radio" },
      { label: "Prototype", value: "1", detail: "full app walkthrough video" },
    ],
    highlights: ["Multi-format home tabs", "Now-playing & lyrics", "Onboarding & verification"],
    process: [
      { title: "Content architecture", body: "Unified home with filter chips for Music, Videos, Podcasts, and Live Radio without separate apps." },
      { title: "Playback UX", body: "Persistent player bar, full-screen playback, and lyrics view with clear hierarchy." },
      { title: "Auth & trust", body: "Splash, login, signup, forgot password, and email/phone verification with consistent dark theme." },
    ],
    outcomes: [
      { title: "Discovery that scales", body: "Charts, artist recommendations, and personalized rows in a single scrollable home." },
      { title: "Premium dark aesthetic", body: "High-contrast typography and imagery suited for entertainment products." },
    ],
    deliverables: ["17+ screens", "Logo & brand mark", "Prototype video"],
    proves: "Consumer mobile UX & entertainment UI",
    coverFile: "Home Music.png",
    extraVideos: [{ src: "/work-assets/crossfade/Crossfade.webm", title: "CrossFade App Walkthrough" }],
    accent: "#F97316",
    accentMuted: "rgba(249, 115, 22, 0.15)",
  },
  {
    slug: "cravely-consumer",
    assetFolder: "fooddeliverycravely",
    order: 5,
    featured: true,
    name: "Cravely Consumer",
    tagline: "Food & grocery discovery app with checkout and address flows",
    category: "Mobile · Food Delivery",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "6 weeks",
    tools: ["Figma", "Prototyping", "User Flows"],
    problem: "Customers need fast restaurant discovery, clear item detail, and frictionless checkout — especially on mobile.",
    summary:
      "Designed the consumer-facing Cravely app: home discovery, restaurant and store listings, item detail, search, checkout, and payment confirmation — complementing the vendor admin platform.",
    metrics: [
      { label: "Screens", value: "8+", detail: "core ordering journey" },
      { label: "Videos", value: "3", detail: "end-to-end flow recordings" },
      { label: "Ecosystem", value: "3", detail: "consumer, vendor, web surfaces" },
    ],
    highlights: ["Discovery home with popular picks", "Restaurant & item detail", "Checkout & payment confirm"],
    process: [
      { title: "Jobs-to-be-done", body: "Optimized for hungry, mobile-first users — minimize taps from open app to order placed." },
      { title: "Listing patterns", body: "Card layouts with ratings, delivery time, and fees visible before tap." },
      { title: "Checkout clarity", body: "Address and payment confirmation separated with review step before submit." },
    ],
    outcomes: [
      { title: "Ecosystem coherence", body: "Consumer UI pairs with Cravely Vendor admin and Cravely Web for full platform story." },
      { title: "Prototype-ready", body: "Recorded flows demonstrate real interaction sequences for stakeholders." },
    ],
    deliverables: ["8+ screens", "3 prototype videos"],
    proves: "Marketplace consumer UX",
    coverFile: "Home.png",
    extraVideos: [
      { src: "/work-assets/fooddeliverycravely/FoodDeliveryAppstart.webm", title: "App Start Flow" },
      { src: "/work-assets/fooddeliverycravely/Fooddeliveryapp1.webm", title: "Ordering Flow 1" },
      { src: "/work-assets/fooddeliverycravely/Fooddeliveryapp2.webm", title: "Ordering Flow 2" },
      { src: "/work-assets/return-order-flow.webm", title: "Return Order Flow" },
    ],
    accent: "#0EA5E9",
    accentMuted: "rgba(14, 165, 233, 0.15)",
  },
  {
    slug: "cravely-web",
    assetFolder: "cravelyweb",
    order: 6,
    featured: false,
    name: "Cravely Web",
    tagline: "Responsive food ordering web experience with menu, cart, and payment",
    category: "Web · Food Delivery",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "5 weeks",
    tools: ["Figma", "Responsive Design", "Web Patterns"],
    problem: "Many users prefer ordering from desktop or mobile web — the experience must match app quality without feeling like an afterthought.",
    summary:
      "Designed Cravely's web ordering flow: restaurant menu with category filters, search, cart sidebar, and payment review — plus full-page marketing and menu exports.",
    metrics: [
      { label: "Web screens", value: "13+", detail: "menu, cart, full-page layouts" },
      { label: "Layout", value: "2-col", detail: "menu + order sidebar pattern" },
    ],
    highlights: ["Menu grid with add controls", "Live order sidebar", "Full responsive web pages"],
    process: [
      { title: "Web-native patterns", body: "Sidebar cart and horizontal category tabs optimized for pointer and keyboard use." },
      { title: "Visual continuity", body: "Aligned typography and components with Cravely mobile for brand consistency." },
    ],
    outcomes: [
      { title: "Desktop ordering", body: "Users browse menu and manage cart without losing context." },
      { title: "Marketing-ready exports", body: "Full-width page designs for landing and menu showcase." },
    ],
    deliverables: ["13+ web frames", "JPG & PNG exports"],
    proves: "Responsive web product design",
    coverFile: "webfull/web-1.png",
    extraVideos: [{ src: "/work-assets/web-cravely.webm", title: "Cravely Web Walkthrough" }],
    accent: "#2563EB",
    accentMuted: "rgba(37, 99, 235, 0.15)",
  },
  {
    slug: "ecommerce-store",
    assetFolder: "ecommercestore",
    order: 7,
    featured: false,
    name: "ELITE Fashion",
    tagline: "Premium fashion e-commerce mobile experience",
    category: "Mobile · Fashion",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "6 weeks",
    tools: ["Figma", "Typography", "Editorial Layout"],
    problem: "Luxury fashion brands need mobile shops that feel editorial — not like generic template stores.",
    summary:
      "Designed ELITE: a high-end fashion app with editorial hero, curated categories, product grid, wishlist, search, cart, checkout, order tracking, and cancellation flows.",
    metrics: [
      { label: "Screens", value: "9+", detail: "shop, cart, orders, auth" },
      { label: "Aesthetic", value: "Editorial", detail: "serif type & architectural imagery" },
    ],
    highlights: ["Editorial homepage", "Product detail & wishlist", "Order tracking & cancellation"],
    process: [
      { title: "Brand-led UI", body: "Serif headlines, generous whitespace, and photography-forward layouts for premium positioning." },
      { title: "Commerce essentials", body: "Full purchase loop without sacrificing luxury feel." },
    ],
    outcomes: [
      { title: "Distinct visual identity", body: "Stands apart from purple/blue delivery apps — shows range across industries." },
      { title: "Complete purchase loop", body: "From browse to confirmation and post-purchase support." },
    ],
    deliverables: ["9+ screens", "Prototype video"],
    proves: "Brand-led mobile commerce",
    coverFile: "Homepage.png",
    extraVideos: [{ src: "/work-assets/ecommercestore/Ecommercestore.webm", title: "ELITE Store Walkthrough" }],
    accent: "#A8A29E",
    accentMuted: "rgba(168, 162, 158, 0.2)",
  },
  {
    slug: "saas-flow",
    assetFolder: "saas-flow",
    order: 8,
    featured: false,
    name: "SaaS Flow",
    tagline: "Mobile workspace for tasks, calendar, and team collaboration",
    category: "Mobile · SaaS",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "4 weeks",
    tools: ["Figma", "Kanban Patterns", "Prototyping"],
    problem: "Remote teams need lightweight task tools on mobile — not stripped-down desktop ports.",
    summary:
      "Designed a mobile-first project workspace: kanban board, task details with subtasks, calendar view, notifications, and success states — clean SaaS aesthetic with priority badges.",
    metrics: [
      { label: "Screens", value: "6+", detail: "board, tasks, calendar" },
      { label: "Patterns", value: "Kanban", detail: "priority, progress, assignees" },
    ],
    highlights: ["Workspace board", "Task detail & subtasks", "Calendar & notifications"],
    process: [
      { title: "Mobile kanban", body: "Vertical task cards with priority, comments, attachments, and assignee avatars." },
      { title: "Micro-interactions", body: "Success states and progress bars communicate completion clearly." },
    ],
    outcomes: [
      { title: "Team-ready mobile SaaS", body: "Demonstrates B2B product thinking beyond admin dashboards." },
    ],
    deliverables: ["6+ screens", "Prototype video"],
    proves: "B2B mobile SaaS patterns",
    coverFile: "Workspace Board (Updated).png",
    extraVideos: [{ src: "/work-assets/saas-flow/SAASflow.webm", title: "SaaS Flow Demo" }],
    accent: "#3B82F6",
    accentMuted: "rgba(59, 130, 246, 0.15)",
  },
  {
    slug: "flex-track",
    assetFolder: "flextrack",
    order: 9,
    featured: false,
    name: "FlexTrack",
    tagline: "Fitness tracking mobile application",
    category: "Mobile · Health",
    categoryGroup: "Product",
    role: "UI/UX Designer",
    timeline: "3 weeks",
    tools: ["Figma", "Mobile UI", "Prototyping"],
    problem: "Fitness apps must motivate without overwhelming — progress should feel immediate and achievable.",
    summary: "Designed FlexTrack mobile screens covering core tracking flows with a focused, activity-first interface.",
    metrics: [
      { label: "Screens", value: "4+", detail: "core user journeys" },
      { label: "Video", value: "1", detail: "app walkthrough" },
    ],
    highlights: ["Activity dashboards", "Clean health UI"],
    process: [{ title: "Activity-first layout", body: "Prioritized daily progress and quick logging over feature bloat." }],
    outcomes: [{ title: "Focused health UX", body: "Readable metrics and clear navigation for on-the-go use." }],
    deliverables: ["4+ screens", "Prototype video"],
    proves: "Health & fitness mobile UX",
    coverFile: "Screen1.png",
    extraVideos: [{ src: "/work-assets/flextrack/FlexTrack.webm", title: "FlexTrack Walkthrough" }],
    accent: "#10B981",
    accentMuted: "rgba(16, 185, 129, 0.15)",
  },
  {
    slug: "digital-agency",
    assetFolder: "digitalagencylandingpage",
    order: 10,
    featured: false,
    name: "Digital Agency",
    tagline: "High-converting agency landing page with projects & social proof",
    category: "Landing Page",
    categoryGroup: "Marketing",
    role: "UI/UX Designer",
    timeline: "2 weeks",
    tools: ["Figma", "Web Design", "Conversion UX"],
    problem: "Agencies need landing pages that build trust fast — hero, work, and testimonials in one scroll.",
    summary:
      "Designed a full agency landing page: hero with CTA, client logos, project grid, testimonial card, and footer — professional blue palette optimized for lead generation.",
    metrics: [
      { label: "Sections", value: "6+", detail: "hero, work, testimonial, CTA" },
      { label: "Goal", value: "Leads", detail: "multiple Start Project CTAs" },
    ],
    highlights: ["Hero + team imagery", "Project showcase grid", "Google testimonial block"],
    process: [{ title: "Conversion structure", body: "Repeated CTAs and social proof placed at decision points throughout the scroll." }],
    outcomes: [{ title: "Client-ready landing", body: "Demonstrates marketing page design for agencies and startups." }],
    deliverables: ["Full landing page design"],
    proves: "Marketing & landing page design",
    coverFile: "landing page and design.png",
    accent: "#2563EB",
    accentMuted: "rgba(37, 99, 235, 0.15)",
  },
  {
    slug: "bouyant",
    assetFolder: "bouyantlandingpage",
    order: 11,
    featured: false,
    name: "Bouyant",
    tagline: "Product landing page design",
    category: "Landing Page",
    categoryGroup: "Marketing",
    role: "UI/UX Designer",
    timeline: "1 week",
    tools: ["Figma", "Web Design"],
    problem: "Startups need a sharp first impression — one screen that communicates value instantly.",
    summary: "Designed the Bouyant landing page with clear hierarchy, modern layout, and conversion-focused structure.",
    metrics: [{ label: "Deliverable", value: "1", detail: "full landing page" }],
    highlights: ["Hero messaging", "Modern web layout"],
    process: [{ title: "Single-page storytelling", body: "Condensed value proposition into one high-impact viewport." }],
    outcomes: [{ title: "Launch-ready creative", body: "Suitable for startup marketing and portfolio marketing pages." }],
    deliverables: ["Landing page UI"],
    proves: "Landing page & visual design",
    coverFile: "landingpage2.png",
    accent: "#6366F1",
    accentMuted: "rgba(99, 102, 241, 0.15)",
  },
  {
    slug: "ridged",
    assetFolder: "ridged-lp",
    order: 12,
    featured: false,
    name: "Ridged",
    tagline: "Brand landing page for product launch",
    category: "Landing Page",
    categoryGroup: "Marketing",
    role: "UI/UX Designer",
    timeline: "1 week",
    tools: ["Figma", "Branding", "Web Design"],
    problem: "Product launches need landing pages that match brand tone and drive signups.",
    summary: "Designed the Ridged landing page — visual identity and layout crafted for a focused product announcement.",
    metrics: [{ label: "Deliverable", value: "1", detail: "landing page design" }],
    highlights: ["Brand-forward layout"],
    process: [{ title: "Launch-focused UI", body: "Single-page design optimized for campaign use." }],
    outcomes: [{ title: "Campaign-ready asset", body: "Ready for development handoff or marketing use." }],
    deliverables: ["Landing page UI"],
    proves: "Marketing landing pages",
    coverFile: "ridgedlandingpage.png",
    accent: "#8B5CF6",
    accentMuted: "rgba(139, 92, 246, 0.15)",
  },
  {
    slug: "skin-muse",
    assetFolder: "skinmuselsndingpage",
    order: 13,
    featured: false,
    name: "Skin Muse",
    tagline: "Beauty e-commerce landing & catalog experience",
    category: "E-commerce · Web",
    categoryGroup: "Marketing",
    role: "UI/UX Designer",
    timeline: "3 weeks",
    tools: ["Figma", "E-commerce", "Web Design"],
    problem: "Beauty brands need elegant catalog and product pages that feel premium on web.",
    summary:
      "Designed Skin Muse landing, makeup landing, product catalog, product detail, and shopping bag — cohesive beauty commerce visuals.",
    metrics: [
      { label: "Screens", value: "5", detail: "landing, catalog, product, bag" },
      { label: "Vertical", value: "Beauty", detail: "makeup & skincare commerce" },
    ],
    highlights: ["Product catalog", "Product page", "Shopping bag"],
    process: [{ title: "Beauty commerce IA", body: "Catalog → product → bag flow with aspirational imagery and clear CTAs." }],
    outcomes: [{ title: "Vertical expertise", body: "Shows adaptability across food, fashion, and beauty industries." }],
    deliverables: ["5 web/mobile screens"],
    proves: "Beauty & lifestyle e-commerce",
    coverFile: "Landing Page.png",
    accent: "#EC4899",
    accentMuted: "rgba(236, 72, 153, 0.15)",
  },
  {
    slug: "infographics",
    assetFolder: "infographics",
    order: 2,
    featured: true,
    name: "Infographics",
    tagline: "Product marketing visuals & data storytelling",
    category: "Visual Design",
    categoryGroup: "Marketing",
    role: "Visual Designer",
    timeline: "Ongoing",
    tools: ["Figma", "Illustration", "Data Viz"],
    problem: "Complex products need simple visuals for pitches, App Store pages, and investor decks.",
    summary:
      "Created infographic suites for multi-vendor food delivery and product features — wheel diagrams, feature breakdowns, charts, and branded marketing frames.",
    metrics: [
      { label: "Assets", value: "44+", detail: "infographics & frames" },
      { label: "Use cases", value: "3+", detail: "pitch, social, product education" },
    ],
    highlights: ["Feature wheel diagrams", "Chart & graph layouts", "Branded marketing frames"],
    process: [{ title: "Simplify complexity", body: "Turned multi-sided platform features into scannable visual narratives." }],
    outcomes: [{ title: "Pitch-ready visuals", body: "Supports sales and marketing for food delivery and SaaS products." }],
    deliverables: ["44+ infographic assets"],
    proves: "Visual storytelling & marketing design",
    coverFile: "infographic.png",
    accent: "#8B5CF6",
    accentMuted: "rgba(139, 92, 246, 0.15)",
  },
  {
    slug: "food-app-logos",
    assetFolder: "foodapplogos",
    order: 15,
    featured: false,
    name: "Food App Logos",
    tagline: "Mobile app icon & logo explorations for food brands",
    category: "Brand Identity",
    categoryGroup: "Brand",
    role: "Brand Designer",
    timeline: "2 weeks",
    tools: ["Figma", "Logo Design", "App Icons"],
    problem: "Food apps compete on store shelves — icon and logo must read instantly at small sizes.",
    summary: "Explored logo and app icon directions for food delivery brands across Android large-format previews and mark variations.",
    metrics: [
      { label: "Concepts", value: "5+", detail: "logo & icon directions" },
      { label: "Formats", value: "App Store", detail: "Android large previews" },
    ],
    highlights: ["App icon concepts", "Frame compositions"],
    process: [{ title: "Icon legibility", body: "Tested marks at small sizes with bold shapes and limited color palettes." }],
    outcomes: [{ title: "Brand exploration", body: "Demonstrates identity work supporting product UI." }],
    deliverables: ["5+ logo/icon concepts"],
    proves: "Brand identity & app icons",
    coverFile: "Frame 11.png",
    accent: "#F59E0B",
    accentMuted: "rgba(245, 158, 11, 0.15)",
  },
  {
    slug: "shoppera-wireframes",
    assetFolder: "wireframing",
    order: 16,
    featured: false,
    name: "Shoppera",
    tagline: "E-commerce wireframes & brand style guide",
    category: "Wireframing · Process",
    categoryGroup: "Process",
    role: "UX Designer",
    timeline: "2 weeks",
    tools: ["Figma", "Wireframing", "IA"],
    problem: "Before visual design, stakeholders need aligned structure — wireframes reduce rework.",
    summary:
      "Created Shoppera desktop wireframe, mobile wireframe, and brand style guide — showing UX process from structure to visual system.",
    metrics: [
      { label: "Deliverables", value: "3", detail: "desktop, mobile, style guide" },
      { label: "Phase", value: "UX", detail: "pre-visual exploration" },
    ],
    highlights: ["Desktop wireframe", "Mobile wireframe", "Brand style guide"],
    process: [{ title: "Structure before polish", body: "Established IA, navigation, and content blocks before high-fidelity UI." }],
    outcomes: [{ title: "Process transparency", body: "Shows hiring teams how you think — not just final pixels." }],
    deliverables: ["Wireframes", "Style guide"],
    proves: "UX process & information architecture",
    coverFile: "Shoppera Desktop Wireframe.png",
    accent: "#64748B",
    accentMuted: "rgba(100, 116, 139, 0.2)",
  },
];
